// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/RangelReale/fproto-wrap-validator-std/validator.proto

/*
Package gwproto is a generated protocol buffer package.

It is generated from these files:
	github.com/RangelReale/fproto-wrap-validator-std/validator.proto

It has these top-level messages:
	FieldValidator
	RepeatedFieldValidator
	OneOfFieldValidator
*/
package gwproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Field validator. In the case of repeated or map, there rules apply to EACH item, not to the repeated field itself.
// For the repeated field itself rules, see RepeatedFieldValidator.
type FieldValidator struct {
	// Whether the field is required.
	Required bool `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
	// Uses a Golang RE2-syntax regex to match the field contents.
	Regex string `protobuf:"bytes,2,opt,name=regex" json:"regex,omitempty"`
	// Only allow the exact string value.
	StringEq string `protobuf:"bytes,20,opt,name=string_eq,json=stringEq" json:"string_eq,omitempty"`
	// Only allow items in this list.
	StringIn []string `protobuf:"bytes,22,rep,name=string_in,json=stringIn" json:"string_in,omitempty"`
	// Only allow items NOT in this list.
	StringNotIn []string `protobuf:"bytes,23,rep,name=string_not_in,json=stringNotIn" json:"string_not_in,omitempty"`
	// Field value of integer strictly greater than this value.
	IntGt int64 `protobuf:"varint,30,opt,name=int_gt,json=intGt" json:"int_gt,omitempty"`
	// Field value of integer strictly smaller than this value.
	IntLt int64 `protobuf:"varint,31,opt,name=int_lt,json=intLt" json:"int_lt,omitempty"`
	// Field value of integer strictly greater than this value.
	IntGte int64 `protobuf:"varint,32,opt,name=int_gte,json=intGte" json:"int_gte,omitempty"`
	// Field value of integer strictly smaller than this value.
	IntLte int64 `protobuf:"varint,33,opt,name=int_lte,json=intLte" json:"int_lte,omitempty"`
	// Field value of integer exactly this value.
	IntEq int64 `protobuf:"varint,34,opt,name=int_eq,json=intEq" json:"int_eq,omitempty"`
	// Only allow items in this list.
	IntIn []int64 `protobuf:"varint,35,rep,packed,name=int_in,json=intIn" json:"int_in,omitempty"`
	// Only allow items NOT in this list.
	IntNotIn []int64 `protobuf:"varint,36,rep,packed,name=int_not_in,json=intNotIn" json:"int_not_in,omitempty"`
	// In the case of enums, only allow defined values, else ignored.
	IntEnumCheck bool `protobuf:"varint,39,opt,name=int_enum_check,json=intEnumCheck" json:"int_enum_check,omitempty"`
	// Field value of double strictly greater than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatGt float64 `protobuf:"fixed64,40,opt,name=float_gt,json=floatGt" json:"float_gt,omitempty"`
	// Field value of double strictly smaller than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatLt float64 `protobuf:"fixed64,41,opt,name=float_lt,json=floatLt" json:"float_lt,omitempty"`
	// Field value of double describing the epsilon within which
	// any comparison should be considered to be true. For example,
	// when using float_gt = 0.35, using a float_epsilon of 0.05
	// would mean that any value above 0.30 is acceptable. It can be
	// thought of as a {float_value_condition} +- {float_epsilon}.
	// If unset, no correction for floating point inaccuracies in
	// comparisons will be attempted.
	FloatEpsilon float64 `protobuf:"fixed64,42,opt,name=float_epsilon,json=floatEpsilon" json:"float_epsilon,omitempty"`
	// Floating-point value compared to which the field content should be greater or equal.
	FloatGte float64 `protobuf:"fixed64,43,opt,name=float_gte,json=floatGte" json:"float_gte,omitempty"`
	// Floating-point value compared to which the field content should be smaller or equal.
	FloatLte float64 `protobuf:"fixed64,44,opt,name=float_lte,json=floatLte" json:"float_lte,omitempty"`
	// Floating-point value compared to which the field content should be equal or whithin the epsilon.
	FloatEq float64 `protobuf:"fixed64,45,opt,name=float_eq,json=floatEq" json:"float_eq,omitempty"`
	// Only allow items in this list.
	FloatIn []float64 `protobuf:"fixed64,46,rep,packed,name=float_in,json=floatIn" json:"float_in,omitempty"`
	// Only allow items NOT in this list.
	FloatNotIn []float64 `protobuf:"fixed64,47,rep,packed,name=float_not_in,json=floatNotIn" json:"float_not_in,omitempty"`
	// Field value of length greater than this value.
	LengthGt int64 `protobuf:"varint,50,opt,name=length_gt,json=lengthGt" json:"length_gt,omitempty"`
	// Field value of length smaller than this value.
	LengthLt int64 `protobuf:"varint,51,opt,name=length_lt,json=lengthLt" json:"length_lt,omitempty"`
	// Field value of length greater than this value.
	LengthGte int64 `protobuf:"varint,52,opt,name=length_gte,json=lengthGte" json:"length_gte,omitempty"`
	// Field value of length smaller than this value.
	LengthLte int64 `protobuf:"varint,53,opt,name=length_lte,json=lengthLte" json:"length_lte,omitempty"`
	// Field value of integer strictly equal this value.
	LengthEq int64 `protobuf:"varint,54,opt,name=length_eq,json=lengthEq" json:"length_eq,omitempty"`
	// Only allow items in this list.
	LengthIn []int64 `protobuf:"varint,55,rep,packed,name=length_in,json=lengthIn" json:"length_in,omitempty"`
	// Only allow items NOT in this list.
	LengthNotIn []int64 `protobuf:"varint,56,rep,packed,name=length_not_in,json=lengthNotIn" json:"length_not_in,omitempty"`
	// Bool must be this value
	BoolEq bool `protobuf:"varint,60,opt,name=bool_eq,json=boolEq" json:"bool_eq,omitempty"`
}

func (m *FieldValidator) Reset()                    { *m = FieldValidator{} }
func (m *FieldValidator) String() string            { return proto.CompactTextString(m) }
func (*FieldValidator) ProtoMessage()               {}
func (*FieldValidator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FieldValidator) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *FieldValidator) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *FieldValidator) GetStringEq() string {
	if m != nil {
		return m.StringEq
	}
	return ""
}

func (m *FieldValidator) GetStringIn() []string {
	if m != nil {
		return m.StringIn
	}
	return nil
}

func (m *FieldValidator) GetStringNotIn() []string {
	if m != nil {
		return m.StringNotIn
	}
	return nil
}

func (m *FieldValidator) GetIntGt() int64 {
	if m != nil {
		return m.IntGt
	}
	return 0
}

func (m *FieldValidator) GetIntLt() int64 {
	if m != nil {
		return m.IntLt
	}
	return 0
}

func (m *FieldValidator) GetIntGte() int64 {
	if m != nil {
		return m.IntGte
	}
	return 0
}

func (m *FieldValidator) GetIntLte() int64 {
	if m != nil {
		return m.IntLte
	}
	return 0
}

func (m *FieldValidator) GetIntEq() int64 {
	if m != nil {
		return m.IntEq
	}
	return 0
}

func (m *FieldValidator) GetIntIn() []int64 {
	if m != nil {
		return m.IntIn
	}
	return nil
}

func (m *FieldValidator) GetIntNotIn() []int64 {
	if m != nil {
		return m.IntNotIn
	}
	return nil
}

func (m *FieldValidator) GetIntEnumCheck() bool {
	if m != nil {
		return m.IntEnumCheck
	}
	return false
}

func (m *FieldValidator) GetFloatGt() float64 {
	if m != nil {
		return m.FloatGt
	}
	return 0
}

func (m *FieldValidator) GetFloatLt() float64 {
	if m != nil {
		return m.FloatLt
	}
	return 0
}

func (m *FieldValidator) GetFloatEpsilon() float64 {
	if m != nil {
		return m.FloatEpsilon
	}
	return 0
}

func (m *FieldValidator) GetFloatGte() float64 {
	if m != nil {
		return m.FloatGte
	}
	return 0
}

func (m *FieldValidator) GetFloatLte() float64 {
	if m != nil {
		return m.FloatLte
	}
	return 0
}

func (m *FieldValidator) GetFloatEq() float64 {
	if m != nil {
		return m.FloatEq
	}
	return 0
}

func (m *FieldValidator) GetFloatIn() []float64 {
	if m != nil {
		return m.FloatIn
	}
	return nil
}

func (m *FieldValidator) GetFloatNotIn() []float64 {
	if m != nil {
		return m.FloatNotIn
	}
	return nil
}

func (m *FieldValidator) GetLengthGt() int64 {
	if m != nil {
		return m.LengthGt
	}
	return 0
}

func (m *FieldValidator) GetLengthLt() int64 {
	if m != nil {
		return m.LengthLt
	}
	return 0
}

func (m *FieldValidator) GetLengthGte() int64 {
	if m != nil {
		return m.LengthGte
	}
	return 0
}

func (m *FieldValidator) GetLengthLte() int64 {
	if m != nil {
		return m.LengthLte
	}
	return 0
}

func (m *FieldValidator) GetLengthEq() int64 {
	if m != nil {
		return m.LengthEq
	}
	return 0
}

func (m *FieldValidator) GetLengthIn() []int64 {
	if m != nil {
		return m.LengthIn
	}
	return nil
}

func (m *FieldValidator) GetLengthNotIn() []int64 {
	if m != nil {
		return m.LengthNotIn
	}
	return nil
}

func (m *FieldValidator) GetBoolEq() bool {
	if m != nil {
		return m.BoolEq
	}
	return false
}

type RepeatedFieldValidator struct {
	// Whether the field is required.
	Required bool `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
	// Field value of length greater than this value.
	LengthGt int64 `protobuf:"varint,12,opt,name=length_gt,json=lengthGt" json:"length_gt,omitempty"`
	// Field value of length smaller than this value.
	LengthLt int64 `protobuf:"varint,13,opt,name=length_lt,json=lengthLt" json:"length_lt,omitempty"`
	// Field value of length greater than this value.
	LengthGte int64 `protobuf:"varint,14,opt,name=length_gte,json=lengthGte" json:"length_gte,omitempty"`
	// Field value of length smaller than this value.
	LengthLte int64 `protobuf:"varint,15,opt,name=length_lte,json=lengthLte" json:"length_lte,omitempty"`
	// Field value of integer strictly equal this value.
	LengthEq int64 `protobuf:"varint,16,opt,name=length_eq,json=lengthEq" json:"length_eq,omitempty"`
	// Only allow items in this list.
	LengthIn []int64 `protobuf:"varint,17,rep,packed,name=length_in,json=lengthIn" json:"length_in,omitempty"`
	// Only allow items NOT in this list.
	LengthNotIn []int64 `protobuf:"varint,18,rep,packed,name=length_not_in,json=lengthNotIn" json:"length_not_in,omitempty"`
}

func (m *RepeatedFieldValidator) Reset()                    { *m = RepeatedFieldValidator{} }
func (m *RepeatedFieldValidator) String() string            { return proto.CompactTextString(m) }
func (*RepeatedFieldValidator) ProtoMessage()               {}
func (*RepeatedFieldValidator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RepeatedFieldValidator) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *RepeatedFieldValidator) GetLengthGt() int64 {
	if m != nil {
		return m.LengthGt
	}
	return 0
}

func (m *RepeatedFieldValidator) GetLengthLt() int64 {
	if m != nil {
		return m.LengthLt
	}
	return 0
}

func (m *RepeatedFieldValidator) GetLengthGte() int64 {
	if m != nil {
		return m.LengthGte
	}
	return 0
}

func (m *RepeatedFieldValidator) GetLengthLte() int64 {
	if m != nil {
		return m.LengthLte
	}
	return 0
}

func (m *RepeatedFieldValidator) GetLengthEq() int64 {
	if m != nil {
		return m.LengthEq
	}
	return 0
}

func (m *RepeatedFieldValidator) GetLengthIn() []int64 {
	if m != nil {
		return m.LengthIn
	}
	return nil
}

func (m *RepeatedFieldValidator) GetLengthNotIn() []int64 {
	if m != nil {
		return m.LengthNotIn
	}
	return nil
}

type OneOfFieldValidator struct {
	// Whether the field is required.
	Required bool `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
}

func (m *OneOfFieldValidator) Reset()                    { *m = OneOfFieldValidator{} }
func (m *OneOfFieldValidator) String() string            { return proto.CompactTextString(m) }
func (*OneOfFieldValidator) ProtoMessage()               {}
func (*OneOfFieldValidator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OneOfFieldValidator) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*FieldValidator)(nil),
	Field:         48771,
	Name:          "validator.field",
	Tag:           "bytes,48771,opt,name=field",
	Filename:      "github.com/RangelReale/fproto-wrap-validator-std/validator.proto",
}

var E_Rfield = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*RepeatedFieldValidator)(nil),
	Field:         48772,
	Name:          "validator.rfield",
	Tag:           "bytes,48772,opt,name=rfield",
	Filename:      "github.com/RangelReale/fproto-wrap-validator-std/validator.proto",
}

var E_Oofield = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.OneofOptions)(nil),
	ExtensionType: (*OneOfFieldValidator)(nil),
	Field:         48773,
	Name:          "validator.oofield",
	Tag:           "bytes,48773,opt,name=oofield",
	Filename:      "github.com/RangelReale/fproto-wrap-validator-std/validator.proto",
}

func init() {
	proto.RegisterType((*FieldValidator)(nil), "validator.FieldValidator")
	proto.RegisterType((*RepeatedFieldValidator)(nil), "validator.RepeatedFieldValidator")
	proto.RegisterType((*OneOfFieldValidator)(nil), "validator.OneOfFieldValidator")
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Rfield)
	proto.RegisterExtension(E_Oofield)
}

func init() {
	proto.RegisterFile("github.com/RangelReale/fproto-wrap-validator-std/validator.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xdb, 0x4f, 0x13, 0x41,
	0x14, 0xc6, 0x53, 0x1a, 0xda, 0xed, 0x70, 0x51, 0x47, 0x84, 0x01, 0x04, 0x97, 0x42, 0x62, 0xbd,
	0x74, 0x37, 0x82, 0xb7, 0x10, 0x13, 0x6f, 0xa9, 0xa4, 0x49, 0x63, 0xcd, 0x3e, 0x98, 0xc8, 0x0b,
	0x59, 0xda, 0xd3, 0x65, 0xe2, 0x30, 0xd3, 0xdd, 0x9e, 0x8a, 0xef, 0xea, 0x8b, 0x7f, 0x9c, 0xff,
	0x91, 0x89, 0x99, 0x99, 0xdd, 0xed, 0x12, 0xb1, 0xc2, 0x13, 0x39, 0xdf, 0xef, 0xcc, 0x37, 0x73,
	0xbe, 0x59, 0xa6, 0xe4, 0x55, 0xc4, 0xf1, 0x64, 0x7c, 0xec, 0xf5, 0xd4, 0xa9, 0x1f, 0x84, 0x32,
	0x02, 0x11, 0x40, 0x28, 0xc0, 0x1f, 0x0c, 0x13, 0x85, 0xaa, 0x79, 0x96, 0x84, 0xc3, 0xe6, 0x97,
	0x50, 0xf0, 0x7e, 0x88, 0x2a, 0x69, 0x8e, 0xb0, 0xef, 0xe7, 0x95, 0x67, 0x5a, 0x68, 0x2d, 0x17,
	0xd6, 0xdc, 0x48, 0xa9, 0x48, 0x80, 0x6f, 0xc0, 0xf1, 0x78, 0xe0, 0xf7, 0x61, 0xd4, 0x4b, 0xf8,
	0x30, 0x6f, 0xae, 0xff, 0xaa, 0x90, 0xc5, 0x77, 0x1c, 0x44, 0xff, 0x63, 0xb6, 0x88, 0xae, 0x11,
	0x27, 0x81, 0x78, 0xcc, 0x13, 0xe8, 0xb3, 0x92, 0x5b, 0x6a, 0x38, 0x41, 0x5e, 0xd3, 0x25, 0x32,
	0x9b, 0x40, 0x04, 0x5f, 0xd9, 0x8c, 0x5b, 0x6a, 0xd4, 0x02, 0x5b, 0xd0, 0x75, 0x52, 0x1b, 0x61,
	0xc2, 0x65, 0x74, 0x04, 0x31, 0x5b, 0x32, 0xc4, 0xb1, 0x42, 0x2b, 0x2e, 0x40, 0x2e, 0xd9, 0xb2,
	0x5b, 0x9e, 0xc0, 0xb6, 0xa4, 0x75, 0xb2, 0x90, 0x42, 0xa9, 0x50, 0x37, 0xac, 0x98, 0x86, 0x39,
	0x2b, 0xbe, 0x57, 0xd8, 0x96, 0xf4, 0x16, 0xa9, 0x70, 0x89, 0x47, 0x11, 0xb2, 0x4d, 0xb7, 0xd4,
	0x28, 0x07, 0xb3, 0x5c, 0xe2, 0x01, 0x66, 0xb2, 0x40, 0x76, 0x27, 0x97, 0x3b, 0x48, 0x57, 0x48,
	0xd5, 0x76, 0x03, 0x73, 0x8d, 0x5e, 0x31, 0xed, 0x90, 0x01, 0x81, 0xc0, 0xb6, 0x72, 0xd0, 0x41,
	0xc8, 0x8c, 0x20, 0x66, 0xf5, 0xdc, 0xa8, 0x15, 0x67, 0x32, 0x97, 0x6c, 0xdb, 0x2d, 0xa7, 0x72,
	0x5b, 0xd2, 0xdb, 0x84, 0x68, 0x39, 0x3d, 0xee, 0x8e, 0x41, 0x0e, 0x97, 0x68, 0xcf, 0xba, 0x43,
	0x16, 0x8d, 0x97, 0x1c, 0x9f, 0x1e, 0xf5, 0x4e, 0xa0, 0xf7, 0x99, 0xdd, 0x35, 0x09, 0xce, 0x6b,
	0x4f, 0x39, 0x3e, 0x7d, 0xab, 0x35, 0xba, 0x4a, 0x9c, 0x81, 0x50, 0xa1, 0x99, 0xa9, 0xe1, 0x96,
	0x1a, 0xa5, 0xa0, 0x6a, 0xea, 0x03, 0x9c, 0x20, 0x81, 0xec, 0x5e, 0x01, 0x75, 0x90, 0x6e, 0x93,
	0x05, 0x8b, 0x60, 0x38, 0xe2, 0x42, 0x49, 0x76, 0xdf, 0xf0, 0x79, 0x23, 0xb6, 0xac, 0xa6, 0xd3,
	0xce, 0xac, 0x81, 0x3d, 0x30, 0x0d, 0x4e, 0xea, 0x0d, 0x13, 0xa8, 0x43, 0x78, 0x58, 0x80, 0x3a,
	0x86, 0x7c, 0x67, 0x88, 0x59, 0xb3, 0xb0, 0x73, 0x2b, 0x9e, 0x20, 0x2e, 0x99, 0xe7, 0x96, 0x73,
	0xd4, 0x96, 0xd4, 0x25, 0x76, 0xff, 0x2c, 0x10, 0xdf, 0x60, 0x62, 0x34, 0x1b, 0xc9, 0x3a, 0xa9,
	0x09, 0x90, 0x11, 0x9e, 0xe8, 0x69, 0x77, 0x4d, 0xc2, 0x8e, 0x15, 0x0e, 0xb0, 0x00, 0x05, 0xb2,
	0xbd, 0x22, 0xec, 0x20, 0xdd, 0x20, 0x24, 0x5f, 0x09, 0xec, 0xb1, 0xa1, 0xb5, 0x6c, 0x29, 0x14,
	0xb0, 0x1e, 0xe7, 0x49, 0x11, 0x77, 0xec, 0xb0, 0x29, 0x86, 0x98, 0x3d, 0x2d, 0x5a, 0xdb, 0x8f,
	0x32, 0x85, 0x5c, 0xb2, 0x67, 0xf6, 0x12, 0xad, 0x60, 0x3f, 0xca, 0x14, 0xa6, 0x43, 0x3d, 0x37,
	0x0d, 0x73, 0x56, 0xb4, 0x53, 0xad, 0x90, 0xea, 0xb1, 0x52, 0x42, 0x7b, 0xbf, 0x30, 0x37, 0x5c,
	0xd1, 0x65, 0x2b, 0xae, 0xff, 0x9c, 0x21, 0xcb, 0x01, 0x0c, 0x21, 0x44, 0xe8, 0x5f, 0xe1, 0x1f,
	0xeb, 0x5c, 0x4a, 0xf3, 0xd3, 0x52, 0x5a, 0x98, 0x9a, 0xd2, 0xe2, 0xf4, 0x94, 0xae, 0x4d, 0x4d,
	0xe9, 0xfa, 0xb4, 0x94, 0x6e, 0xfc, 0x2f, 0x25, 0xfa, 0x57, 0x4a, 0xf5, 0x47, 0xe4, 0x66, 0x57,
	0x42, 0x77, 0x70, 0xf9, 0x20, 0xf6, 0x3f, 0x90, 0xd9, 0x81, 0xee, 0xa6, 0x1b, 0x9e, 0x7d, 0xbc,
	0xbc, 0xec, 0xf1, 0xf2, 0x8c, 0x4b, 0x77, 0x88, 0x5c, 0xc9, 0x11, 0xfb, 0xf6, 0x5b, 0x3f, 0x41,
	0x73, 0xbb, 0xab, 0xde, 0xe4, 0xfd, 0x3b, 0xbf, 0x4d, 0x60, 0x8d, 0xf6, 0x0f, 0x49, 0x25, 0xb9,
	0x94, 0xe5, 0xf7, 0xd4, 0x72, 0xab, 0x60, 0x79, 0xf1, 0x55, 0x06, 0xa9, 0xe3, 0xfe, 0x27, 0x52,
	0x55, 0xea, 0x5f, 0xe6, 0x5d, 0x09, 0x6a, 0x90, 0x99, 0xff, 0x48, 0xcd, 0x37, 0x0b, 0xe6, 0x17,
	0x64, 0x13, 0x64, 0x7e, 0x6f, 0x5e, 0x1f, 0xbe, 0xbc, 0xf2, 0x4f, 0x41, 0xa4, 0xb4, 0xe8, 0x47,
	0x67, 0xf6, 0x0c, 0x15, 0xf3, 0x67, 0xef, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0xbc, 0x9f,
	0x13, 0x54, 0x06, 0x00, 0x00,
}
